// app/blog/page.tsx
import React from "react";
import Image from "next/image";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { TypewriterEffectSmooth } from "@/components/ui/TypeWriterEffect";
import { TextGenerateEffect } from "@/components/ui/GenerateEffect";
import Link from "next/link";

function BlogPage() {
  return (
    <main className="flex flex-col h-screen items-start justify-start px-12 sm:px-24 py-10">
      <div className="w-full h-full items-start">
        <div className="flex z-10 w-full items-center justify-center font-mono text-sm">
          <div className="flex h-5 items-center space-x-4 text-sm">
            <Link href="/blog">
              <Button variant="ghost">Blog</Button>
            </Link>
            <Separator orientation="vertical" />
            <Link href="/">
              <Button variant="outline" className="text-green-500">
                Fres Space
              </Button>
            </Link>
            <Separator orientation="vertical" />
            <Link href="/about">
              <Button variant="ghost">About</Button>
            </Link>
          </div>
        </div>
        <Separator className=" my-10" />
      </div>
      <div className="h-full w-screen justify-start">
        <h1 className="text-start text-white font-bold text-4xl">
          All my <span className="text-green-500">posts</span>{" "}
        </h1>
      </div>
    </main>
  );
}

export default BlogPage;

// src/routes/blog/+page.svelte
<script lang="ts">
  import { Separator } from "$lib/components/ui/separator";
  /*
  import { BlogPost } from "$lib/components/BlogPost.svelte";
  const posts: Post[] = [
    {
      id: 1,
      title: "Post1",
      description: "Description Post 1",
      tags: [
        { text: "Typescript", color: "sky-400" },
        { text: "Hono", color: "orange-500" },
        { text: "Bun", color: "slate-300" },
      ],
      date: "2024-08-25",
      image: "",
    },
  ];
    */
</script>

<main class="flex flex-col h-full w-full max-w-6xl items-start justify-start">
  <h1 class="font-serif font-bold text-4xl">
    <span class="text-green-500">B</span>log
  </h1>
  <Separator class="my-4" />
  <p>Currently busy...😴</p>
</main>
