// components/Navbar.tsx
import Link from "next/link";
import React from "react";
import { Button } from "./ui/button";
import { Separator } from "./ui/separator";

function Navbar() {
  return (
    <div className="w-full h-full items-start">
      <div className="flex z-10 w-full items-center justify-center font-mono text-sm">
        <div className="flex h-5 items-center space-x-4 text-sm">
          <Button variant="ghost">
            <Link href="/blog">Blog</Link>
          </Button>
          <Separator orientation="vertical" />
          <Button variant="outline" className="text-green-500">
            <Link href="/">Fres Space</Link>
          </Button>
          <Separator orientation="vertical" />
          <Button variant="ghost">
            <Link href="/about">About</Link>
          </Button>
        </div>
      </div>
      <Separator className=" my-10" />
    </div>
  );
}

export default Navbar;

// src/lib/components/Navbar.svelte
<script lang="ts">
import Separator from "./ui/separator/separator.svelte";
import Button from "./ui/button/button.svelte";
</script>
    <div class="w-full h-full items-start">
      <div class="flex z-10 w-full items-center justify-center font-mono text-sm">
        <div class="flex h-5 items-center space-x-4 text-sm">
          <Button variant="ghost">
            <a href="/blog">Blog</a>
          </Button>
          <Separator orientation="vertical" />
          <Button variant="outline" class="text-green-500">
            <a href="/">Fres Space</a>
          </Button>
          <Separator orientation="vertical" />
          <Button variant="ghost">
            <a href="/about">About</a>
          </Button>
        </div>
      </div>
      <Separator class=" my-10" />
    </div>
